# config/routes.yaml

index:
    path: /
    controller: App\Controller\MainController::index

main:
    path: /main
    controller: App\Controller\MainController::index

addAutor:
    path: /addAutor
    controller: App\Controller\AutorController::index

addBook:
    path: /addBook
    controller: App\Controller\BookController::index


# ziskávání dat pro zobrazení
api_get_autors:
    path: /api/autors
    controller: App\Controller\AutorController::getAutors
    methods: GET

api_knihy:
    path: /api/knihy
    controller: App\Controller\BookController::getKnihy
    methods: GET


# posílání dat pro databázi
api_create_autors:
    path: /api/autors
    controller: App\Controller\AutorController::create
    methods: POST

api_create_books:
    path: /api/books
    controller: App\Controller\BookController::create
    methods: POST




# Route to get the details of a book
get_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::getKniha
    methods: GET

# Route to update a book
update_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::updateKniha
    methods: PUT

# Route to delete a book
delete_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::deleteKniha
    methods: DELETE



# get book detail autor, book
book_detail:
    path: /api/knihaDetail/{id}
    controller: App\Controller\BookdetailController::getBookDetail
    methods: GET
    

    
# Catch-all route to handle frontend routing
frontend:
    path: /{reactRouting}
    controller: App\Controller\MainController::index
    requirements:
        reactRouting: .*




