# config/routes.yaml

index:
    path: /
    controller: App\Controller\MainController::index

main:
    path: /main
    controller: App\Controller\MainController::index

addAutor:
    path: /addAutor
    controller: App\Controller\AddautorController::index

addBook:
    path: /addBook
    controller: App\Controller\AddbookController::index

# ziskávání dat pro zobrazení
api_get_autors:
    path: /api/autors
    controller: App\Controller\AutorController::getAutors
    methods: GET

api_knihy:
    path: /api/knihy
    controller: App\Controller\KnihaController::getKnihy
    methods: GET

# posílání dat pro databázi
api_create_autors:
    path: /api/autors
    controller: App\Controller\AddautorController::create
    methods: POST

api_create_books:
    path: /api/books
    controller: App\Controller\AddbookController::create
    methods: POST



# Route to get the details of a book
get_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::getKniha
    methods: GET

# Route to update a book
update_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::updateKniha
    methods: PUT

# Route to delete a book
delete_kniha:
    path: /api/kniha/{id}
    controller: App\Controller\BookdetailController::deleteKniha
    methods: DELETE


# Catch-all route to handle frontend routing
frontend:
    path: /{reactRouting}
    controller: App\Controller\MainController::index
    requirements:
        reactRouting: .*